### ISSUE TITLE
QA Craft install & content updates on staging

### ISSUE THREAD

**Issue by jkvill1** [CityOfBoston/onebostonday#23] opened 2018-04-05 14:05 UTC

**Comment by ChristopherAlberto-SRX** [comment] 2018-04-06 19:04
A sweep of all frontend tools in the CMS have been checked.
There were some naming issues that came up but nothing that will hold back content from being able to be successfully updated. We will track these separately in our local bug tracking software.

The only thing holding up the update at the moment is the exporting tool which is currently being fixed. Once that change is in and verified QA will review this ticket again before closing.

**Comment by ChristopherAlberto-SRX** [comment] 2018-04-13 15:02
Exporting tool is working as intended now along with all other CMS frontend tools.

**Closed as completed by ChristopherAlberto-SRX** 2018-04-13 15:02 UTC
